In [2]:
import numpy as np

def is_diagonally_dominant(A):
    n = A.shape[0]
    
    for i in range(n):
        diagonal = abs(A[i][i])
        row_sum = sum(abs(A[i][j]) for j in range(n) if j != i)
        
        if diagonal < row_sum:
            return False
            
    return True


A1 = np.array([[4, 1, 2],
               [1, 3, 1],
               [0, 1, 5]])

print(f"Is the matrix diagonally dominant? {is_diagonally_dominant(A1)}")
print(A1)

Is the matrix diagonally dominant? True
[[4 1 2]
 [1 3 1]
 [0 1 5]]
